falconServers:
    transfer:
        - 10.189.20.26:6060
        - 10.189.20.27:6060
        - 10.189.20.28:6060
    graph:
        - 10.189.20.21:6071
        - 10.189.20.22:6071
        - 10.189.20.23:6071
        - 10.189.20.24:6071
    alarm:
        - 10.189.20.26:9912
        - 10.189.20.27:9912
        - 10.189.20.28:9912
    judge:
        - 10.189.20.26:6801
        - 10.189.20.27:6801
        - 10.189.20.28:6801
    aggregator:
        - 10.189.20.26:6055
    nodata:
        - 10.189.20.26:6090
    hbs:
        - 10.189.20.21:6031
        - 10.189.20.22:6031
        - 10.189.20.23:6031
        - 10.189.20.24:6031
#    gateway:
#        - 10.130.63.71:16060
#        - 10.130.63.72:16060
    kafka_consumer:
        - 10.189.20.26:6850
        - 10.189.20.27:6850
        - 10.189.20.28:6850
    trend:
        - 10.189.20.21:6991
        - 10.189.20.22:6991
        - 10.189.20.23:6991
        - 10.189.20.24:6991
falconCounterMetrics:
    transfer:
        RecvCnt: qps
        SendToJudgeCnt: qps
        SendToTsdbCnt: qps
        SendToGraphCnt: qps
        SendToKafkaCntTotal: qps
        SendToKafkaCnt: qps
        SendToKafkaCnt_vipfalcon-dba: qps
        SendToJudgeFailCnt: qps
        SendToTsdbFailCnt: qps
        SendToGraphFailCnt: qps
        SendToKafkaFailCntTotal: qps
        SendToKafkaFailCnt: qps
        SendToKafkaFailCnt_vipfalcon-dba: qps
        SendToJudgeDropCnt: qps
        SendToTsdbDropCnt: qps
        SendToGraphDropCnt: qps
        SendToKafkaDropCnt: qps
        SendToKafkaDropCnt_vipfalcon-dba: qps
        JudgeSendCacheCnt: cnt
        TsdbSendCacheCnt: cnt
        GraphSendCacheCnt: cnt
        KafkaSendCacheCnt: cnt
        KafkaSendCacheCnt_vipfalcon-dba: cnt
        SendToRedisCnt: cnt
        SendToRedisFailCnt: cnt
    graph:
        GraphRpcRecvCnt: qps
    kafka_consumer:
        ConsumeCnt: qps
        ConsumeDropCnt: qps
        SendToTrendCnt: qps
        SendToTrendDropCnt: qps
        SendToTrendFailCnt: qps
        TrendSendCacheCnt: cnt
        SendToTransferCnt: qps
        SendToTransferDropCnt: qps
        SendToTransferFailCnt: qps
        TransferSendCacheCnt: cnt
    trend:
        RpcRecvCnt: qps
        WriteToDBCnt: qps
        WriteToDBFailCnt: qps
        RpcKeyTooSmallCnt: cnt
        RpcKeyTooBigCnt: cnt
        RcpCacheHistoryFullCnt: cnt
        RpcRecvGuegeCnt: cnt
        RpcRecvCounterCnt: cnt
    judge:
        MetricsCnt: cnt

tsdbServer: 10.189.20.29:4242
httpLister: 0.0.0.0:8838
debug: true
